### ISSUE TITLE
Unsupported instrument

### ISSUE THREAD

**Issue by severak** [truj/midica#71]
I am not able to play anything or to save is as audio.

Error message is:

> Unsupported instrument: Piano 1 bank #0 preset#

Also when this message is thrown, it looks like it's improssible to close player window.

**Comment by truj** [comment]
Thank you for reporting this.
However I need some more information to reproduce the problem.

- Did you load any soundfont? If yes, which one?
- Can you provide the file you imported?
- Which file extension and Audio Export Settings did you use for the export?
- Which OS and Java version do you use?

**Comment by severak** [comment]
> Did you load any soundfont? If yes, which one?

it don't work both with and without soundfont. When I used soundfont, I used tiny_Carillon.sf2 and GeneralUser GS MuseScore v1.442.sf2 (this is from MuseScore website)

> Can you provide the file you imported?

https://github.com/truj/midica/blob/master/examples/old_macdonald_had_a_farm.midica

(and some Alda files I have on disc)

> Which file extension and Audio Export Settings did you use for the export?

wav

> Which OS and Java version do you use?

Windows 7

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by truj** [comment]
On Windows I can reproduce the problem. (I use Linux usually.)
It occurs in the player as well. Seems to be a gervill-related problem.
I'll check that.

**Comment by truj** [comment]
On windows, gervill uses a default DLS soundbank instead of a default SF2 soundbank.
DLS is not yet supported in Midica.
Probably it will take me a few days to fix this.

Until then, the following workarounds are possible:
- use 1.3.2: https://github.com/truj/midica/releases/tag/1.3.2 (if you don't need audio export)
- use a different OS than Windows (if you need audio export)

**Comment by truj** [comment]
I think I fixed it.
At least it's now running for me in the following combinations:
- Windows 10 / Java 13
- Linux / OpenJDK 8
- Linux / OpenJDK 16
- Linux / Oracle Java 8

Can you please try out if your combination (Windows 7 / Java 1.8) works as well with release [1.4.1](https://github.com/truj/midica/releases/tag/1.4.1)

**Comment by severak** [comment]
Now everything works. Thanks for fixing.
